name: stack-bitcoin

services:
  lightningd:
    image: lightningd-custom:latest
    build:
      context: .
      dockerfile: Dockerfile.lightningd
    container_name: lightningd
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximum 10 Megabytes per file
        max-file: "3"     # Only saves the last 3 files
    volumes:
      # BACKUP
      - /mnt/backup_cln:/backup_usb
      # CONFIG & DATA
      - ./config/cln_config:/root/.lightning/config
      - ./data/cln:/root/.lightning/bitcoin
      - tor-data:/data/.tor:ro
    ports:
      - "3001:3001"
    networks:
      net:
        ipv4_address: 10.20.0.2
      transit:
    command:
      - --alias=${NODE_ALIAS}
      - --network=bitcoin
      - --log-level=info
      - --clboss-min-channel=1000000
      - --clboss-max-rebalance-fee-ppm=250
      - --clboss-auto-close=false

  bitcoind:
    image: lncm/bitcoind:v26.0
    container_name: bitcoind
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    stop_grace_period: 5m  # Gives 5 minutes for graceful shutdown
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximum 10 Megabytes per file
        max-file: "3"     # Only saves the last 3 files
    volumes:
      - ./data/bitcoin:/data/.bitcoin
    networks:
      net:
        ipv4_address: 10.20.0.3
      transit:
    command:
      - -server=1
      - -dbcache=8000
      - -prune=20000        # This limits block storage to ~20GB
      - -txindex=0          # Saves space (not needed for CLN)
      - -prune=20000        # Keeps ~20GB of blocks (adjust if you want more)
      - -printtoconsole=1
      - -proxy=10.254.0.2:9050 # Route all P2P traffic through Tor
      - -listen=0           # Disable incoming P2P connections
      - -rpcuser=bitcoind.user      # Put the user you want
      - -rpcpassword=bitcoind.pass  # Put the password you want
      - -rpcallowip=10.20.0.0/24
      - -rpcbind=0.0.0.0

  rtl:
    image: shahanafarooqui/rtl:v0.15.8
    container_name: rtl
    restart: unless-stopped
    depends_on:
      - lightningd
    environment:
      - RTL_CONFIG_PATH=/data
    volumes:
      - ./data/rtl:/data
    ports:
      - "3000:3000"
    networks:
      net:
        ipv4_address: 10.20.0.4

  teosd:
    image: teosd:latest
    container_name: teosd
    restart: always
    depends_on:
      - bitcoind
    volumes:
      - ./data/teos:/home/teos/.teos
      - tor-data:/data/.tor:ro
    command: ["teosd"]
    networks:
      net:
        ipv4_address: 10.20.0.5
      transit:

networks:
  net:
    name: bastion-bitcoin
    ipam:
      config:
        - subnet: 10.20.0.0/24
  transit:
    name: bastion-transit
    external: true

volumes:
  tor-data:
    name: bastion-tor-data
    external: true